name: Update Awesome Rust stats

on:
  schedule:
    - cron: "0 6 * * *" # runs at 06:00 UTC everyday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Install dependencies
        run: go get .

      - name: Run
        run: go run main.go
        env:
          PAT: ${{ secrets.PAT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
          OTEL_SERVICE_NAME: ${{ vars.OTEL_SERVICE_NAME }}
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
          FILE_SUFFIX: "latest"

      - name: Set last update date
        run: |
          current_day=$(date +"%Y-%m-%d")
          echo "${current_day}" > "last-update.txt"

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Push generated csv files to the repo
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update stats"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - name: Upload results
        uses: actions/upload-artifact@v6
        with:
          name: generated-stats-csv
          path: |
            ./*.csv
            ./last-update.txt
